name = "Erdos892"
defaultTargets = ["Erdos892"]

[leanOptions]
autoImplicit = false
relaxedAutoImplicit = false
linter.mathlibStandardSet = true

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"
rev = "f369f66ea08e49c46a2fffaceb6699e6bef11555"

[[lean_lib]]
name = "Erdos892"
